import { sidebar } from "vuepress-theme-hope";

export const zhSidebar = sidebar({
  "/posts/": [
    "personal-site-seo-guide",
    "custom-writing-skills-tutorial",
    "frontend-container-config-injection",
    "distributed-robot-inspection-system",
    "1248-binary-conversion",
    "gitlab-runner-setup",
    "hyper-v-embedded-linux-dev",
    "linux-gpio-guide",
    "linux-socket-and-process",
    "modbus-rs485-guide",
    "rs485-serial-communication-guide",
    "static-vs-dynamic-libraries",
    "writing-workflow-replication",
    "iec-61499-industrial-automation",
    "web3-ton-development-tips",
    "solidity-digital-bonsai-nft",
    "monaco-editor-websocket-debug",
    "frontend-table-export-merge-3",
    "frontend-table-export-merge-1",
    "svg-doodle-component",
    "nestjs-connect-mongodb",
    "nodejs-novel-crawler-nestjs-proxy",
    "git-panic-room",
    "package-manager-battle",
    "aliyun-ecs-java-web-env",
    "ccaa-offline-downloader",
    "weengine-on-ecs",
    "mediawiki-setup",
    "hackintosh-simple-guide",
    "frontend-table-export-merge-2",
    {
      text: "Polymarket",
      prefix: "polymarket/",
      collapsible: true,
      children: [
        "polymarket-trading-bot-intro",
        "polymarket-api-guide",
        "polymarket-websocket-orderbook",
        "polymarket-gnosis-safe-proxy",
        "polymarket-batch-orders",
        "polymarket-bot-dev-journey",
        "polymarket-strategy-pivot",
        "prediction-market-vs-finance",
        "polymarket-market-making-strategy",
        "polymarket-binance-arbitrage",
        "polymarket-risk-management",
        "prediction-market-future",
      ],
    },
  ],
  "/": [
    "",
    "intro",
  ],
});
